### ISSUE TITLE
Details checklist

### ISSUE THREAD

**Issue by dccowan** [ubcgif/E3D#1]
Some some small details that should be address before publishing:

- [ ] Does this code use -iwt or iwt convention and is this correct in theory section?
- [ ] Are references and equations linked properly in theory?
- [ ] All example files and downloads correct
- [ ] Are loop defined CW or CCW (explain in survey file)
- [ ] Do the same number of receiver and frequencies need to be used in formatting obs file?
